<?xml version="1.0" encoding="utf-8"?><Database Name="muzyka" Class="DatabaseMusicDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\Rafal\Desktop\Shit\Inż\baza\muzyka.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="Audio_Organiser.Properties.Settings" SettingsPropertyName="muzykaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Song" Member="Song">
    <Type Name="Song">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Artist" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>